<Project>
  <PropertyGroup>
    <Version>1.5.1</Version>
    <AssemblyVersion>1.5.1.0</AssemblyVersion>
    <FileVersion>1.5.1.0</FileVersion>
    <Company>KioskWatchdog</Company>
    <Product>Kiosk Watchdog</Product>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
